# Site settings
title: Ruiqi Chen's website
brand: Ruiqi Chen's website          # 专门给导航栏左上角用（你想显示的固定名称）
email: ruiqi.chen@vub.be
description: "
  Department of Electronics and Informatics (ETRO)<br>
  Vrije Universiteit Brussel (VUB)<br>
  1050 Elsene, Brussels, Belgium"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

google_scholar: "https://scholar.google.com/citations?user=X-VB7JyO7-EC"
orcid: "https://orcid.org/0000-0001-6837-5675"
researchgate: "https://www.researchgate.net/profile/Ruiqi-Chen-7"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: 
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""